# Generated by Django 5.2.1 on 2025-07-02 09:15

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meine_app', '0007_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('events', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='meine_app.events')),
            ],
        ),
    ]
