# Generated by Django 5.2.1 on 2025-07-02 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meine_app', '0005_profile'),
        ('meine_app', '0009_voteevents'),
    ]

    operations = [
    ]
